### ISSUE TITLE
Этот метод не нужен

### ISSUE THREAD

**Issue by toofast73** [Ziggismunt/MT#10]
https://github.com/Ziggismunt/MT/blob/59eaf27e4c83f242f6e1ded1458c8810a26257d9/src/main/java/com/mt/oep/data/AccountRepository.java#L43

Ты возвращаешь Account, а в нем уже лежат деньги. Не нужно ходить за ними повторно.

**Comment by Ziggismunt** [comment]
Ok, deleted
