### ISSUE TITLE
MoneyTransfer => MoneyTransferService

### ISSUE THREAD

**Issue by toofast73** [Ziggismunt/MT#3]
https://github.com/Ziggismunt/MT/blob/ccf29596500d7ffd572c232994a4040b30789358/src/main/java/com/mt/oep/back/MoneyTransfer.java#L5

MoneyTransfer sounds like an instance of a transaction.
MoneyTransferService is better -- it provides some methods for making payments

**Comment by Ziggismunt** [comment]
Renamed
