### ISSUE TITLE
Rename DataModel

### ISSUE THREAD

**Issue by toofast73** [Ziggismunt/MT#5]
https://github.com/Ziggismunt/MT/blob/ccf29596500d7ffd572c232994a4040b30789358/src/main/java/com/mt/oep/data/DataModel.java#L6

DataModel sounds too general -- responsibilities of this class are not obvious.
AccountRepository, which is responsible for storing and retrieving of accounts is a good candidate.

**Comment by Ziggismunt** [comment]
Renamed
