### ISSUE TITLE
Make it accept an Account class and work with it

### ISSUE THREAD

**Issue by toofast73** [Ziggismunt/MT#8]
https://github.com/Ziggismunt/MT/blob/ccf29596500d7ffd572c232994a4040b30789358/src/main/java/com/mt/oep/back/MoneyTransfer.java#L12

Now your service knows only about ID and asks repository/database/dao about its state. So the AccountRepository class will be too complex. 

Proper responsibilities:
AccountRepository knows only how to save and find an account by ID.
MoneyTransferService is responsible for checking the account's state and validation. You may even extract validation logic to a separate AccountValidator class. Think about it.

**Comment by Ziggismunt** [comment]
Done
