### ISSUE TITLE
Не убедила

### ISSUE THREAD

**Issue by toofast73** [Ziggismunt/MT#9]
https://github.com/Ziggismunt/MT/blob/59eaf27e4c83f242f6e1ded1458c8810a26257d9/src/test/java/com/mt/oep/back/MoneyTransferServiceTest.java#L110

Тебе нужно создавать не new Thread, а Runnable. А все Runnables нужно положить в один Executors.newFixedThreadPool(100).

Когда ты вызываешь у треда run он начинает исполнение в ТЕКУШЕМ потоке. Поэтому ты сделала 30 последовательных операций и не проверила что-либо. Sad, but true.

**Comment by Ziggismunt** [comment]
Fixed
